site_name: circleci-feeback
docs_dir: docs
repo_name: GitHub
repo_url: https://github.com/codingdiaz/circleci-feedback
edit_uri: edit/master/docs/docs
theme:
  name: 'readthedocs'
nav:
    - 'Getting Started': 'getting_started.md'
    - 'Architecture': 'architecture.md'